### ISSUE TITLE
Installation not working.

### ISSUE THREAD

**Issue by vipin12117** [adifucan/m2-baler#4]
When i tried to install from magento command and its just give errors

[InvalidArgumentException] There are no commands defined in the "setup" namespace.

**Comment by adifucan** [comment]
Do you get this error while running php `bin/magento` command? To enable/disable module, you need to run `bin/magento config:set dev/js/enable_baler_js_bundling <1|0> `

**Comment by vipin12117** [comment]
I tried all but same errors

**Comment by adifucan** [comment]
I’ll take a look but if `bin/magento` command fails with this error, most like `bin/magento config:set dev/js/enable_baler_js_bundling <1|0>` command is not the cause if the error because all `bin/magento` commands do not execute.

**Comment by adifucan** [comment]
This error is definitely not caused by `Magento_Baler` module. I just reinstalled Magento community edition 2.3.3 with enabled `Magento_Baler` module. This error does not occur. Try to run `bin/magento list` command to get more meaningful error message. Go to product page. If it fails check your `var/log/*` for the error message.
